### ISSUE TITLE
Unclear deprecation of ios.bundleIdentifier and android.package

### ISSUE THREAD

**Issue by actuallymentor** [expo/eas-cli#1050]
### Summary

The `eas` CLI deprecated using `ios.bundleIdentifier` and `android.package` for ejected projects as per #407 (where @dsokal requested I open an issue).

The CLI however does not link to any resources or docs as to how to handle this deprecation. The PR indicates:

> However, I think if someone decides to go for a bare project, they should be able to change those values on their own (with Xcode/Android Studio)

As an expo user I can confirm this is not the case. The whole reason I fell in love with Expo is that I never need to touch Xcode or AS.

Ejection is an action of necessity, not desire. In my case, react native Firebase requires a custom development client with native code. That doesn't mean I know what to do with this deprecation message.

I would like to suggest linking to relevant resources to take the required actions. Additionally, those resources should make it clear how this info in handles. I personally am extra confused by the fact that the `ios.bundleIndentifier` **does** seem to be used by `eas build` (else I have no idea where it got that identifier from).

### Managed or bare?

bare

### Environment

```
expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v16.14.0/bin/yarn
      npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
      Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8139111
      Xcode: 13.3/13E113 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      eas-cli: 0.48.2
      expo-cli: 5.3.0
    Expo Workflow: bare
```

### Error output

```
Specifying "android.package" in app.config.js is deprecated for bare workflow projects.
EAS Build depends only on the value in the native code. Please remove the deprecated configuration.
```

and

```
Specifying "ios.bundleIdentifier" in app.config.js is deprecated for bare workflow projects.
EAS Build depends only on the value in the native code. Please remove the deprecated configuration.
```

### Reproducible demo or steps to reproduce from a blank project

N/A

**Comment by kbrandwijk** [comment]
There's two separate issues here in my opinion:
- The first is that the CLI has no idea whether the native files that are found are the result of running `expo prebuild`, in which case it makes perfect sense that those values exist in the configuration (native files are usually not persisted in this scenario, so need to be regenerated from config like you mentioned). Following through what the warning says would break future prebuilds.
- The second is, that if you decide to _stick_ with a bare workflow, there not much documentation on how to update these manually in native code. We could definitely add that to the docs.

Outside of these two issues, I see a third issue going on: you 'ejected' to the bare workflow because you wanted to make native code modifications to support firebase. With config plugins and development builds, those reasons shouldn't be forcing you to go with the bare workflow at all, meaning that if you would do the modifications through a config plugin, you would be able to stay in managed workflow and not have this issue of manually changing bundle/package ids to begin with...

**Comment by actuallymentor** [comment]
> The first is that the CLI has no idea whether the native files that are found are the result of running expo prebuild

Sounds like a needed CLI flag?

> The second is, that if you decide to stick with a bare workflow, there not much documentation on how to update these manually in native code

I think that is the proximal issue I ran into

> those reasons shouldn't be forcing you to go with the bare workflow at all, meaning that if you would do the modifications through a config plugin

This was my assumption, I never realised I ejected at all until someone pointed to the fact that `expo prebuild --clean` ejects you.

**Comment by wkozyra95** [comment]
> which means these properties should definitely not be deleted from our configs?

You don't need to delete them, but those values will be ignored by eas. From eas build perspective native code is a source of truth, if you want to sync those values you can run prebuild again but depending on your changes in native code it might fail.

The main idea behind config plugins is removing the use-case you are describing, if someone wants to have a full react-native project then they need to manage it, but if you want to make just some small native change then the recommended way is to stay on managed and resolve the issue via config plugins.

> ios.bundleIndentifier does seem to be used by eas build (else I have no idea where it got that identifier from).

bundle identifier is read from `ios/appname.xcodeproj/project.pbxproj`

> I would like to suggest linking to relevant resources to take the required actions

In general, I agree but note that when we deprecated that the EAS Build was still in preview/beta phase and when ejecting you should refer to android and react-native documentation.

> Sounds like a needed CLI flag?

That would require as to support both bare projects and bare project that are very similar to clean ejected projects(even defingin what that means is problematic), we could do that in 2 ways:
 - just run prebuild before build(it could fail for a lot of reasons)
 - implement separate logic for synchronizing native files with app.json with would be huge amount of work
 
 neither of those options make sense when compared to alternative (config plugins)

**Comment by actuallymentor** [comment]
> You don't need to delete them, but those values will be ignored by eas.

I quote from the CLI: `Please remove the deprecated configuration.`

> bundle identifier is read from ios/appname.xcodeproj/project.pbxproj

Yes *BUT* that is generated by `expo prebuild` which uses `app.config.js`.

> when we deprecated that the EAS Build was still in preview/beta

Fair, but it is not now in preview is it?

> just run prebuild before build

I do that now, but it took me 2 days of trial and error to reach the conclusion that I can ignore the deprecation warning.

> neither of those options make sense when compared to alternative (config plugins)

I don't understand: are you saying I don't need to be ejected because of the plugins, or are you saying that _ideally in the future_ I wouldn't need to eject?

**Comment by kbrandwijk** [comment]
- Yes, the warning needs to be updated to something more generic that fits with the 'prebuild' scenario (something like 'Native files detected: changes to ios.bundleidentifier will be ignored until native files are regenerated' or something to that effect)

- No, you _currently_ do not need to be ejected because the changes you made to the native files can be made with a config plugin.

**Comment by actuallymentor** [comment]
- want me to PR that change?
- does not mean these docs are false on the need for prebuild?
https://rnfirebase.io/#expo

**Comment by wkozyra95** [comment]
> Fair, but it is not now in preview is it?

breaking change was made in preview, as far as public version goes nothing was deprecated because as long as it was public it was never supported

> Yes BUT that is generated by expo prebuild which uses app.config.js.

If you have bare project we treat it as any react-native project, from eas perspective it does not matter how it was created

> I do that now, but it took me 2 days of trial and error to reach the conclusion that I can ignore the deprecation warning.

I understand that this is problematic, but we structured messages this way to discourage usage like that. `prebuild` technically can be rerun on existing, but it's not sth we want support.

> I don't understand: are you saying I don't need to be ejected because of the plugins, or are you saying that ideally in the future I wouldn't need to eject?

It's ready now and you can use it, but either you or the library author needs to implement the plugin
