### ISSUE TITLE
[iOS] Failed to find matching arch for input file

### ISSUE THREAD

**Issue by batiste-dek** [expo/eas-cli#1057]
### Build/Submit details page URL

https://expo.dev/accounts/louis-energic/projects/my-project/builds/36460a1f-9f32-4d9f-9f12-0c2c655548e4

### Summary

We ran into this error upgrading our application from SDK 41 to 44. It happens again on the blank template created by `expo init my-project`. We're getting this error trying to run the build on the Simulator, and it has previously been rejected by Apple. We never got this issue before.

### Managed or bare?

managed 

### Environment

expo-env-info 1.0.2 environment info:
    System:
      OS: Linux 5.13 Ubuntu 20.04.4 LTS (Focal Fossa)
      Shell: 5.8 - /usr/bin/zsh
    Binaries:
      Node: 12.22.7 - ~/.nvm/versions/node/v12.22.7/bin/node
      npm: 8.3.1 - ~/.nvm/versions/node/v12.22.7/bin/npm
    npmPackages:
      expo: ~44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.49.0
      expo-cli: 5.3.0
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

```
expo init my-project
eas build
```

**Comment by kbrandwijk** [comment]
The build log you shared shows a successful build. Could you clarify what the issue is?

**Comment by batiste-dek** [comment]
Starting with this SDK, we are having issues deploying or testing in on iOS 15. My coworker has filed an issue on the forum https://forums.expo.dev/t/app-denied-from-appstore-app-signing-issue/62433/7 for our production application, but since I'm running into this issue on a boilerplate app, I'm thinking the issue isn't from our code.

Thanks for your help @kbrandwijk

**Comment by HugDoggyDogg** [comment]
Dear @kbrandwijk,
Thanks for your answer.
The details of our issue can be found in [this ticket](https://forums.expo.dev/t/app-denied-from-appstore-app-signing-issue/62433) I started a few weeks ago on Expo's forum.
To summarize, the build completes but we can't run the app on iOS 15+ devices. As it happens also with a MRE, we believe the issue is somewhere in Apple config files, certificates, provisioning profiles... But nothing we could do had any impact.
Thanks for your time and help !!

**Comment by batiste-dek** [comment]
@kbrandwijk Would you have ideas by any chance ? Thanks for your help

**Comment by HugDoggyDogg** [comment]
Hello @kbrandwijk, a little update on our issue.

We proceeded with upgrade to SDK 45 but the same problem still occurs with iOS.
We haven't been able to publish any update on our app other than OTAs since we opened this issue, and now on top of that our current version of the SDK (41) got deprecated and we are unable to even test it on Expo Go before publishing OTAs.

We also tried contacting Apple Developer Technical Support (DTS) but they _"support developers using Apple-authored tools and frameworks only"_ and thus are sending us back to you guys.

What is bothering us is that we ran into the same issue with a blank project as @batiste-dek mentioned. We also tried deleting our Apple credentials and profile and let EAS creating fresh ones but the signing seems not to be working there either because we are still getting a value of CodeDirectory = 20200 and can't install the build on iOS emulators. However it runs perfectly on local dev mode on ios, android and web.

![The error when trying to launch the installed build](https://aws1.discourse-cdn.com/business5/uploads/expo/original/3X/e/d/edef844f0336f5470feb6530f255255307724c75.jpeg)

[Our build](https://expo.dev/accounts/louis-energic/projects/energic-v2/builds/4a18e805-cc69-44aa-8496-4be8ce69fbad) from yesterday ran with basically latest versions of all softwares :
```
Installed software:
- Xcode 13.3.1 (13E500a)
- Node.js 16.13.2
- Yarn 1.22.17
- pnpm 7.0.0
- npm 8.1.2
- fastlane 2.205.2
- CocoaPods 1.11.3
- Ruby 2.7
- Expo CLI 5.4.4
```

So we are more stuck then ever now that we can't even test our app... We really need your help please :(

**Comment by batiste-dek** [comment]
Hi @kelley-sharp thanks for your response.

The issue is that our application has been refused multiple times by Apple Store, for a crash in iPads it seems. We have been able to reproduce this issue, by downloading our builds and trying to put it on the iPad simulator, which gives us the `Failed to find matching arch for input file` as shown on the screenshot Hugo added. We are guessing that the issue is coming from code signing.


We tried it again today, by using `eas build` on a Linux machine, after wiping certificates both on EAS and Apple servers, which means that all certificates have been created by EAS. The build can be found here: https://expo.dev/accounts/louis-energic/projects/energic-v2/builds/e1e7a8b2-ed57-4d49-9234-0ddebb08683f

Locally, `expo doctor` gives me no warning. Below the results of `eas diagnostics`. 
```

  EAS CLI 0.53.0 environment info:
    System:
      OS: Linux 5.13 Ubuntu 20.04.4 LTS (Focal Fossa)
      Shell: 5.8 - /usr/bin/zsh
    Binaries:
      Node: 12.22.7 - ~/.nvm/versions/node/v12.22.7/bin/node
      npm: 8.11.0 - ~/.nvm/versions/node/v12.22.7/bin/npm
    Utilities:
      Git: 2.36.1 - /usr/bin/git
    npmPackages:
      @expo/webpack-config: ~0.16.21 => 0.16.24 
      expo: ^45.0.0 => 45.0.4 
      expo-dev-client: ^0.9.5 => 0.9.6 
      expo-updates: ~0.13.1 => 0.13.1 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.53.0
      expo-cli: 5.4.7
    Project workflow: managed
```

Dependencies

```
"dependencies": {
    "@expo/react-native-action-sheet": "3.9.0",
    "@expo/vector-icons": "^13.0.0",
    "@miblanchard/react-native-slider": "^1.5.0",
    "@react-native-masked-view/masked-view": "^0.2.6",
    "@react-navigation/bottom-tabs": "^6.3.1",
    "@react-navigation/drawer": "^6.4.1",
    "@react-navigation/material-top-tabs": "^6.2.1",
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/stack": "^6.2.1",
    "@sentry/react-native": "^3.4.2",
    "@tech_energic/rn-tourguide": "1.0.2",
    "axios": "^0.21.1",
    "expo": "^45.0.0",
    "expo-app-loading": "~2.0.0",
    "expo-application": "~4.1.0",
    "expo-asset": "~8.5.0",
    "expo-av": "~11.2.3",
    "expo-barcode-scanner": "~11.3.0",
    "expo-camera": "~12.2.0",
    "expo-clipboard": "~3.0.1",
    "expo-constants": "~13.1.1",
    "expo-dev-client": "^0.9.5",
    "expo-device": "~4.2.0",
    "expo-file-system": "~14.0.0",
    "expo-font": "~10.1.0",
    "expo-image-picker": "~13.1.1",
    "expo-intent-launcher": "~10.2.0",
    "expo-linear-gradient": "~11.3.0",
    "expo-linking": "~3.1.0",
    "expo-localization": "~13.0.0",
    "expo-mail-composer": "~11.2.0",
    "expo-media-library": "~14.1.0",
    "expo-notifications": "~0.15.2",
    "expo-permissions": "~13.2.0",
    "expo-secure-store": "~11.2.0",
    "expo-status-bar": "~1.3.0",
    "expo-store-review": "~5.2.0",
    "expo-tracking-transparency": "~2.2.0",
    "expo-updates": "~0.13.1",
    "expo-web-browser": "~10.2.0",
    "i18n-js": "^3.2.1",
    "jest": "^26.6.3",
    "jshashes": "^1.0.7",
    "moment": "^2.22.2",
    "react": "17.0.2",
    "react-countdown": "^2.3.0",
    "react-native": "0.68.2",
    "react-native-calendar-picker": "^7.1.2",
    "react-native-circular-progress": "^1.0.1",
    "react-native-controlled-mentions": "^2.2.5",
    "react-native-gesture-handler": "~2.2.1",
    "react-native-hyperlink": "0.0.19",
    "react-native-keyboard-aware-scroll-view": "^0.9.1",
    "react-native-markdown-display": "github:vlad-x/react-native-markdown-display",
    "react-native-pager-view": "5.4.15",
    "react-native-progress": "^5.0.0",
    "react-native-reanimated": "~2.8.0",
    "react-native-redash": "^12.1.3",
    "react-native-safe-area-context": "4.2.4",
    "react-native-screens": "~3.11.1",
    "react-native-svg": "12.3.0",
    "react-native-tab-view": "^3.1.1",
    "react-native-web": "0.17.7",
    "react-redux": "^8.0.1",
    "redux": "^4.0.0",
    "redux-saga": "^1.0.2",
    "seamless-immutable": "^7.1.3",
    "sentry-expo": "^4.0.0",
    "socket.io-client": "^2.0.3"
  }
```

eas.json
```
{
  "build": {
    "production": {
      "node": "14.19.3",
      "releaseChannel": "production"
    },
    "preview": {
      "extends": "production",
      "releaseChannel": "staging",
      "distribution": "internal"
    },
    "development": {
      "extends": "production",
      "developmentClient": true,
      "distribution": "internal"
    }
  },
  "cli": {
    "version": ">= 0.52.0"
  }
}
```
