### ISSUE TITLE
eas branch:list "TypeError: Cannot read properties of undefined (reading 'length')"

### ISSUE THREAD

**Issue by evelant** [expo/eas-cli#1339]
### Summary

Running `eas branch:list` results in `TypeError: Cannot read properties of undefined (reading 'length')`

eas cli version: `eas-cli/2.0.0 darwin-arm64 node-v16.16.0`

### Managed or bare?

managed

### Environment

expo-env-info:
```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 3.2.0 - ~/.nvm/versions/node/v16.16.0/bin/yarn
      npm: 7.18.1 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /Users/imagio/.rvm/rubies/ruby-3.1.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: Chipmunk 2021.2.1 Patch 2 Chipmunk 2021.2.1 Patch 2
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 2.0.0
      expo-cli: 6.0.5
    Expo Workflow: managed
```

doctor:
```
Some dependencies are incompatible with the installed expo package version:
 - @react-native-picker/picker - expected version: 2.4.2 - actual version installed: 2.4.4
 - react-native-reanimated - expected version: ~2.9.1 - actual version installed: 2.10.0
 - react-native-safe-area-context - expected version: 4.3.1 - actual version installed: 4.3.3
 - react-native-svg - expected version: 12.3.0 - actual version installed: 12.4.4
 ```

### Error output

`TypeError: Cannot read properties of undefined (reading 'length')`

### Reproducible demo or steps to reproduce from a blank project

Unsure how to repro. Doesn't happen on a blank fresh project. Happens on my project id `cdac4cd6-7959-4b1a-b879-c2f667e6e750`

**Comment by sheikx1221** [comment]
getting the same error
`eas channel:list

Name  com.coolconnectuk.driver
ID    7ff0d051-47df-4585-82f5-16797915f936
    TypeError: Cannot read properties of undefined (reading 'length')
`

**Comment by nappa0326** [comment]
I have the same problem. And "Our code broke" message appears when selecting Deployments menu in expo.dev.

**Comment by Lerosen** [comment]
Same issued for me using the `channel:list` command, the error happens when the second channel ist listed. 
Also I get the following error in my dev client which might be related.

![Screenshot_20221202-222312.png](https://user-images.githubusercontent.com/20213986/205392604-eff8811b-d132-44fb-ad7e-16e69ca6bc41.png)

**Comment by teewuane** [comment]
I'm following [this official guide](https://docs.expo.dev/eas-update/eas-update-and-eas-cli/) and am getting this error on the `eas channel:list`

**Comment by tvillafane** [comment]
seeing the same with 3.3.2 and node v16.14.2

in general not having the best time with EAS.

**Comment by quinlanj** [comment]
There are two classes of errors mentioned in this issue:
1. `reading 'branchMappingLogic'` undefined error: Fixed in https://github.com/expo/eas-cli/pull/1653 , available in the next patch release.
2. `reading 'length'` undefined error: Caused in old versions of `eas-cli` for users with branches that have no updates yet. If the problem still persists in the newest version (>3.4.1), please post your findings in this thread with your repro steps and error outputs.

**Comment by quinlanj** [comment]
Closing this issue as most ppl's concerns have been addressed. Feel free to make another issue if you are still experiencing a problem!
