### ISSUE TITLE
I would like to generate an .apk file, to do that I need to have the SHA1 key that eas build are using to generate the .aab file

### ISSUE THREAD

**Issue by ildaneta** [expo/eas-cli#1551]
### Build/Submit details page URL

https://expo.dev/accounts/ildaneta/projects/Picblink

### Summary

I'm running into a problem when I submit the .aab file generated using `eas build -p android` into Play Store.
I realized that the problem is when the .aab file is converted into a .apk file.

I would like to generate a .apk file to test it and understand what is going on.

To generate a .apk file with the .aab file generated by eas build, I need to run this command:

```bundletool build-apks --bundle=./android/app/build/outputs/bundle/release/app-release.aab --output=~/Downloads/app.apks --mode=universal --ks=./android/app/production-android.keystore --ks-key-alias=production-android --ks-pass=pass:pass; mv ~/Downloads/app.apks ~/Downloads/app.zip;```

But if I generate a new SHA1 key will be different from the expo.

I need to understand how transform this .aab into a .apk file.

### Managed or bare?

Bare

### Environment

```ts
 expo-env-info 1.0.5 
environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.20.1 - ~/.nvm/versions/node/v14.20.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v14.20.1/bin/yarn
      npm: 6.14.17 - ~/.nvm/versions/node/v14.20.1/bin/npm
      Watchman: 2022.10.10.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
      Android SDK:
        API Levels: 30, 31, 33
        Build Tools: 29.0.2, 30.0.3, 31.0.0, 33.0.0
        System Images: android-27 | Google APIs ARM 64 v8a, android-28 | Google APIs ARM 64 v8a, android-28 | Google ARM64-V8a Play ARM 64 v8a, android-29 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.17 => 46.0.17 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.9 
    npmGlobalPackages:
      eas-cli: 2.7.1
      expo-cli: 6.0.6
    Expo Workflow: bare
````

### eas.json file

```
{
  "cli": {
    "version": ">= 2.7.1"
  },
  "build": {
    "development": {
      "distribution": "internal",
      "android": {
        "gradleCommand": ":app:assembleDebug"
      },
      "ios": {
        "buildConfiguration": "Debug"
      }
    },
    "preview": {
      "distribution": "internal",
      "channel": "preview"
    },
    "production": {
      "channel": "production"
    }
  },
  "submit": {
    "production": {}
  }
}
```

### Error output

When Play Store convert the .aab file into a .apk file, I can't communicate my app with the AWS API.
But this problem only happens with Android, into App Store my app works fine.

### Reproducible demo or steps to reproduce from a blank project

Have a project with Expo Bare Workflow and AWS, generate a .aab file and put it on Play Store.

If I install my app from Android Studio with the build variants Release, everything works fine, the problem only happens when the .aab file is turned into .apk file.

When I'm generating the .aab file, I'm not specifying which environment I want, which in this case would be production, I don't know if that would have to do with the problem.

**Comment by wkozyra95** [comment]
It's not clear from your post what is not working. In one place you are saying that you can't submit app to play store and in another that the app can't communicate with api that verifies cert fingerprint that was used to sign your app. So which is it?

When you upload app to the Play store it's signed with one certificate, but the app that is visible to users it's signed with a different one, so the fingerprints of those apps will be different if you install it via play store or from apk. You can check both fingerprints in the play console.

If you are creating apk from aab you are signing it again with new certificate, if you want it to have the same fingerprint as aab you need to use the same keystore that was used during the build. You can download it from the website https://expo.dev/accounts/ildaneta/projects/Picblink/credentials or using `eas credentials` command

I see you have 2 keystores, if you have a problem with submitting app to the store it might be because you are using a wrong key. (legacy one is what was used in expo-cli)

**Comment by ildaneta** [comment]
@wkozyra95 thank you for answering me.
I'll try it. 🙂
