### ISSUE TITLE
EAS Build on Android is Failing (Build tools version 33.0.1 is corrupted) 

### ISSUE THREAD

**Issue by Saad-Bashar** [expo/eas-cli#1652]
### Build/Submit details page URL

https://expo.dev/accounts/shiftcare/projects/shiftcare/builds/17aafd90-2f2a-4c5b-9968-276d64113a29

### Summary

After I update my buildToolsVersion to 33.0.1, the EAS build for android is failing. I needed to update the buildToolsVersion as we are targeting SDK 33 now. (Android 13)

![Screenshot_2023-01-24_at_11 49 06_AM](https://user-images.githubusercontent.com/13269141/214488203-83de52f7-dcaf-4f3d-9fd8-021fc9fab0d5.png)

I had similar issue in my local as well but then I followed this thread from stack overflow and solved it. https://stackoverflow.com/questions/68387270/android-studio-error-installed-build-tools-revision-31-0-0-is-corrupted

### Managed or bare?

Bare

### Environment

``` expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.1/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
      Watchman: 2022.11.28.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8512546
      Xcode: 13.4/13F17a - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 3.4.0```

### Error output

_No response_

### Reproducible demo or steps to reproduce from a blank project

NA

**Comment by wkozyra95** [comment]
It looks like this is an intentional breaking change, if you renamed those files that were suggested in stackoverflow post you linked, this is just a workaround, the proper fix is to update your android gradle plugin.

https://android-developers.googleblog.com/2018/04/android-studio-switching-to-d8-dexer.html
https://stackoverflow.com/questions/68397703/installed-build-tools-revision-31-0-0-is-corrupted-remove-and-install-again-usi
