### ISSUE TITLE
Can't use `policy: appVersion` for `runtimeVersion` and test on a simulator simulaneously without a rebuild on the servers

### ISSUE THREAD

**Issue by ethanj20** [expo/eas-cli#1713]
### Summary

We would like to use `policy: appVersion` as the `runtimeVersion` in `app.config.js` per [this documentation](https://docs.expo.dev/eas-update/runtime-versions/#appversion-runtime-version-policy-available-in-sdk-46-and-higher) but the builds won't run on a simulator when this is set (they only run if the `runtimeVersion` is set to `sdkVersion`, or if the `runtimeVersion` is deleted entirely). Is this the expected workflow? I don't want to have to rebuild my app on expo servers every time I want to test a change, but `appVersion` is the best policy for us as we manage our OTA updates based on the `appVersion`. 

Is there a way to use this `runtimePolicy` without having to delete it from `app.config.js` before trying to run it on a simulator?

### Managed or bare?

Managed

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6.2
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.13.0 - /usr/local/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.19.3 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^47.0.0 => 47.0.13 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ~0.18.9 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.5.2
      expo-cli: 6.0.8
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

1. setup a basic expo react native project
2. set `runtimeVersion: {policy: 'appVersion'} in `app.config.js`
3. attempt to run on simulator, where you will get the error that the dev-client is required. however, the same error is not thrown if `runtimeVersion: {policy: 'sdkVersion'} in `app.config.js`

**Comment by wkozyra95** [comment]
> attempt to run on simulator,

I assume that you are talking about running your app in Expo Go. Is that correct?

This is a correct behavior, Expo Go has multiple runtimes for each SDK, but if you set appVersion policy then Expo Go has no idea what to run it on. You need to use dev-client if you have a custom runtime version.

>  I don't want to have to rebuild my app on expo servers every time I want to test a change

You don't have to, you only need to rebuild dev client when your runtime version changes, or you have native changes.

**Comment by ethanj20** [comment]
Yes that is correct, attempting to run it on Expo Go on a simulator.

Understood. I think we are going to stick with the `sdkVersion` policy for now, even though we will have rebuilds in our app (as we are continuously updating things in our app config at the moment). 

Another quirk: the latest version of the Expo SDK is `47.0.13`, but in the `app.config.js`, it is required that the `sdkVersion = '47.0.0'`, not `'47.0.13'`. Is this expected behavior? Is the `app.config.js` just wanting to know the primary version, not the primary, secondary, and tertiary?

Seems odd to me that ExpoGo wouldn't be able to accept a different runtime other than specific sdkVersions, but that is something we can work around for now.

Thanks for the insight.

**Comment by wkozyra95** [comment]
There is no SDK 47.0.13, this is just a version of an expo package SDK versions are just one number. (it's 47.0.0 instead of just 47 just for legacy reasons)

e.g. if you have Expo Go that supports SDK 47 you can theoretically use any version of expo package 47.x.x , ExpoGo includes only one runtime per SDK

**Comment by ethanj20** [comment]
Makes sense - appreciate the support.

**Comment by quinlanj** [comment]
Update: We'll be lifting the restrictions on this in the coming SDK 49 release. Expo Go will open your project as long as you have a compatible expo SDK version installed, and will no longer look at your runtime version policy anymore. 

Since you are using a managed workflow, this next section won't apply to you, but please note that if your app relies on custom native code that isn't supported in Expo Go (bare workflow), it will try to load your project, but if your JS code references a custom module that isn't bundled in Expo Go, you will receive an error. More details [here](https://docs.expo.dev/bare/using-expo-client/).
