### ISSUE TITLE
Request for documentation on .easignore and requireCommit in eas.json

### ISSUE THREAD

**Issue by andy-HM** [expo/eas-cli#1757]
Hello,

I am writing to request better documentation on the usage of `.easignore` and the `requireCommit` property in the `eas.json`.  I am finding that documentation in these areas are severely lacking in the Expo documentation.  

At the time of writing this, there are 0 results returned from searching "easignore" in the[ Expo documentation site](https://docs.expo.dev/). 

Searching for "requireCommit" does return results in the search but those are mostly instances where `requireCommit` appears in examples of `eas.json`.

What I am looking for is:

1. How does one properly use `.easignore`
2. How does `requireCommit` behave when set to `false`? When set to false in my case, the uploaded files are half the size as when set to true.  Then the build fails because files are missing.
3. Do these two functions work together?  Are they separate?
4. Any other best practices in these areas

Thank you.

**Comment by wkozyra95** [comment]
https://expo.fyi/eas-build-archive

1. In the root of a repository (it replaces all dockerfiles), but .easignore is subdirectories do not do anything(.dockerignore works the same way)
2. false is a default
3. No, `.easignore` does not work with with `requireCommit: true`. `requireCommit: true` is making shallow clone using git(so it can't respect .easignore), and `requireCommit: false` is packaging files using our implementations that slightly diverges from git specs. 
4. Don't use .easignore, we added it because it was quite common request, but there is always a better approach. Also `requireCommit: true` would also be consider a best practice, but it was to annoying for some workflows, so we changed the default to false.

You can use `eas build:inspect --stage archive to check what will be uploaded)

**Comment by andy-HM** [comment]
hello @wkozyra95 thank you for the reply!  This is incredibly helpful.  I was not aware of this level of documentation on Github for Expo.

**Comment by dtx** [comment]
@wkozyra95's reply should be a part of the documentation. lol.

**Comment by macksal** [comment]
I was bitten by this - previously using `.easignore` but it stopped applying after setting `requireCommit: true`. This is a little confusing: `requireCommit` feels like it would a safety feature to make sure the working tree isn't dirty, not a fundamental change to the archiving method.

Would it be appropriate to print a warning if `requireCommit: true` is specified while a `.easignore` file is also present?

**Comment by bj97301** [comment]
if i understand it correctly, if theres one file i want to be included in my build(google-services.json) i should duplicate my .gitignore file and then remove the file(s) i want to be included in the build.  So for me just the google-services.json file. Sounds about right?
