### ISSUE TITLE
Misleading CLI message during EAS Submit iOS outage

### ISSUE THREAD

**Issue by shrihari1999** [expo/eas-cli#1783]
### Build/Submit details page URL

https://expo.dev/accounts/shrihari1999/projects/tinderly/builds/2513ff4a-3f8d-4f11-a86f-a87d9121adbb

### Summary

There is an ongoing EAS Submit outage for iOS. Reason: Accessing iOS credentials and App Store entries may report the App Store portal is under maintenance.
![image](https://user-images.githubusercontent.com/13913674/231147795-ed9622b6-f416-416c-9a68-defdcdb4439d.png)

When running ```eas build -p ios --auto-submit```, the build part is successful, but the submit part fails. The CLI should correctly communicate this by saying something like "Build in progress... Submission Failed..." etc.

Instead, it gives a misleading message that says "Build request failed" as shown in image
![eas](https://user-images.githubusercontent.com/13913674/231142114-0c44e635-a7eb-4ce4-ad7a-c102a4084239.jpg)

If one really things build failed and runs the command again, they are going to end up with multiple builds, for which they will be billed 2$ per build as well!

### Managed or bare?

Managed

### Environment

```npx expo-env-info```
  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 4.15 Ubuntu 16.04.7 LTS (Xenial Xerus)
      Shell: 4.3.48 - /bin/bash
    Binaries:
      Node: 16.17.0 - ~/.config/nvm/versions/node/v16.17.0/bin/node
      Yarn: 1.22.19 - ~/.config/nvm/versions/node/v16.17.0/bin/yarn
      npm: 8.15.0 - ~/.config/nvm/versions/node/v16.17.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    npmPackages:
      expo: ^48.0.4 => 48.0.4 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.6 => 0.71.6 
      react-native-web: ~0.18.7 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.9.1
      expo-cli: 6.3.1
    Expo Workflow: managed

```npx expo-doctor```
✔ Validating global prerequisites versions passed
✔ Checking for incompatible packages passed
✔ Checking for conflicting global packages in project passed
✔ Verifying prebuild support package versions are compatible passed
✔ Checking dependency versions for compatibility with the installed Expo SDK passed
✔ Validating Expo Config passed
✔ Checking package.json for common issues passed

Didn't find any issues with the project!

### Error output

I am not pasting error output as I cannot afford running ```eas build ``` again, sorry. I'm a free user and i can't waste my quota.

### Reproducible demo or steps to reproduce from a blank project

1. EAS Submit outage for iOS must exist or must be simulated. Displayed outage was "Accessing iOS credentials and App Store entries may report the App Store portal is under maintenance."
2. Run ```eas build -p ios --auto-submit```
3. Observe misleading error message in terminal
![eas](https://user-images.githubusercontent.com/13913674/231144000-94ce6135-f848-4135-a6e0-3a7239b1f525.jpg)

**Comment by byCedric** [comment]
Hi @shrihari1999! The error from the image states that the EAS Build couldn't be started successfully. I can't double-check this since you didn't provide a link to the build or submissions. What I could validate is that with `eas-cli@3.9.1` I could successfully build _and_ submit to the app store. But, I did have to accept a few new policies on Apple's side, through https://appstoreconnect.apple.com/

Hope this helps!

**Comment by shrihari1999** [comment]
Sorry @byCedric ! Thank you for your quick response. I've edited my post to include the EAS Build link. Here it is: https://expo.dev/accounts/shrihari1999/projects/tinderly/builds/2513ff4a-3f8d-4f11-a86f-a87d9121adbb. It was a successful build, which was started as a result of the command in the image

I could submit this build separately by using ```eas submit``` at a later time (https://expo.dev/accounts/shrihari1999/projects/tinderly/submissions/a9688910-76da-4b1b-a2d0-5e03b9264a48)

But I can confirm that at that point of time, maybe because of the outage, the submission did **not** start automatically, and the CLI showed misleading message.

**Comment by wkozyra95** [comment]
> But I can confirm that at that point of time, maybe because of the outage, the submission did not start automatically, and the CLI showed misleading message.

This does not seem to be related to the apple issue, it's most likely just a network error when sending a build request.
- EAS CLI sends build request
- Our backend receives a build request, but there is some network error or timeout before a response is delivered.
- Our backend scheduled a build, bud response never reached a CLI.
- From a cli perspective build was not started, and there is no way to verify that because build id would be generated server side. Submission would be scheduled in the next request, but because build request failed, then submission was never scheduled.

In a scenario like that message is technically correct, because HTTP request to start the build failed, it just failed late enough that build was started. It's not ideal but handling that better would require significant API changes for relatively low gain.

**Comment by shrihari1999** [comment]
Understood and makes sense @wkozyra95. If you guys are confident it's a one-off and rare issue, its okay.

If the CLI stores any logs in my PC that might help, I'm happy to dig that up for you too.

**Comment by shrihari1999** [comment]
It just happened again in the **latest** expo-cli version 3.10.0
![eas](https://user-images.githubusercontent.com/13913674/233591188-23369a81-b4f9-4fff-8857-9adf0f37c9f6.jpg)

Tried creating development build using ```eas build --profile development --platform ios```. The build seems to run properly [https://expo.dev/accounts/shrihari1999/projects/tinderly/builds/ad2c9bbc-386c-4ecd-9a9c-ae58c33233bd](here). But got failed message again.

It is not so rare then @wkozyra95 .

**Comment by wkozyra95** [comment]
> It is not so rare then

I didn't say it's rare, I said it's caused by a network error. Network error could be caused by load on our infrastructure, or by your internet connection, or any infrastructure between you and our servers.

We have some work on potential mitigation that should make those errors less likely, but to avoid cases like this entirely we would need to add a retry logic that would require non-trivial changes in our API, which we are considering, but it's not in immediate plans.
