### ISSUE TITLE
Error: GraphQL request failed

### ISSUE THREAD

**Issue by KomailShah05** [expo/eas-cli#2081]
### Summary

Getting error with each eas command. 
Error: GraphQL request failed

### Managed or bare?

Managed

### Environment

npx expo-env-info   
npm ERR! code ETIMEDOUT 
npm ERR! syscall connect
npm ERR! errno ETIMEDOUT
npm ERR! network request to https://registry.npmjs.org/expo-env-info failed, reason: connect ETIMEDOUT 2606:4700::6810:1f22:443
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\abc\AppData\Local\npm-cache\_logs\2023-10-09T11_25_41_839Z-debug-0.log

npx expo-doctor
npm ERR! code ETIMEDOUT 
npm ERR! syscall connect
npm ERR! errno ETIMEDOUT
npm ERR! network request to https://registry.npmjs.org/expo-doctor failed, reason: connect ETIMEDOUT 2606:4700::6810:1f22:443
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\abc\AppData\Local\npm-cache\_logs\2023-10-09T11_26_58_933Z-debug-0.log

### Error output

 Error: GraphQL request failed

### Reproducible demo or steps to reproduce from a blank project

eas build -p android

**Comment by codegien** [comment]
I am facing the same issue can anyone help

**Comment by KomailShah05** [comment]
> I am facing the same issue can anyone help

Issue was with my node  18.15.0 npm was not working fine even I run
` npm i -g eas-cli ` So I downgrade my node version to 16.17.0 and everything goes well

**Comment by quinlanj** [comment]
@KomailShah05 are you running your command with a network VPN or are you behind any kind of firewall (company, country, etc)?

**Comment by ladyshaitan** [comment]
I've been running into this issue as well off and on starting in early October.  I seem to get it for various reasons and none of them are obvious since this error is so vague.  Here are three incidents where I ran into this issue and how they were solved:

October 9th, in this example I was trying to do it on my laptop and using my VPN to work out of the US did the trick:
https://discord.com/channels/695411232856997968/920032594232500225/1160999517496287313

October 12th, in this example it was in a CI pipeline and just went away in a few days.  
https://discord.com/channels/695411232856997968/920032594232500225/1162146040351305778

Today (November 9th) I saw this error again, the problem ended up being that the `EXPO_TOKEN` hadn't been added to the pipeline.  To figure this out I had done `export DEBUG=*` right before running my eas update command and inspected the logs where I found an unauthorized network error.

<img width="788" alt="Screenshot 2023-11-09 at 6 40 08 PM" src="https://github.com/expo/eas-cli/assets/10492916/0ff6fc32-e8f9-49cc-9f92-74c78aa7cb26">

**Comment by szdziedzic** [comment]
Hi,

It looks like general info with your network because you can't connect to npm either. I can't replicate it and it doesn't seem connected to EAS CLI itself. Therefore I will close the issue.

**Comment by miguel-neto-deel** [comment]
Faced this issue. Turned off a VPN connection and it worked.

**Comment by raahimkhan** [comment]
I am getting the same error. And no there are no network issues.

**Comment by eusouoviana** [comment]
Getting this error. No network issues, no VPN.

**Comment by joenguyen0109** [comment]
I have the same issue, no network issue. I had checked with two different networks.

**Comment by onlyargon** [comment]
i have the same issue

**Comment by jsieders** [comment]
For me it was becouse i had made my .nvmrc on Windows and the version that got reported was ��v18.20.2
Remade the file and it was running fine.

**Comment by maniac-tech** [comment]
Has anyone found any resolution to this so far ?

**Comment by katayama8000** [comment]
I suggest updating the access tokens.
