### ISSUE TITLE
Local builds for windows

### ISSUE THREAD

**Issue by Rodrigo-N-Duarte** [expo/eas-cli#2164]
### Do you understand that any feature requests opened in this repository will be closed?

Yes

**Comment by szdziedzic** [comment]
As a workaround, if you want to run `--local` builds on Windows, you can try using [WSL](https://learn.microsoft.com/en-us/windows/wsl/install. Note that WSL technically is not officially supported(we do not test it), but it seems to work well.

What is your use case? If you would like to just build the app with the Expo framework and not use the Expo Application Services (this is a separate thing) you can use [`npx expo:run` command](https://docs.expo.dev/more/expo-cli/#compiling) instead of `eas build --local`.

**Comment by Rodrigo-N-Duarte** [comment]
@szdziedzic my use case is just debbug my app after build or using development build without using EAS, unfortunally can't native build locally on windows, I'll try using WSL
