### ISSUE TITLE
EAS build fails at apple authentication 

### ISSUE THREAD

**Issue by sirusbaladi** [expo/eas-cli#2272]
### Summary

Running eas build --profile production  --platform ios

Fails with:

 Logged in New session
Authentication with Apple Developer Portal failed!
Apple provided the following error info:
Service not available because of maintenance activities, please try again after some time.

I've updated:
npm install -g eas-cli

### Managed or bare?

Managed

### Environment

N/A

### Error output

Authentication with Apple Developer Portal failed!
Apple provided the following error info:
Service not available because of maintenance activities, please try again after some time.

### Reproducible demo or steps to reproduce from a blank project

run eas build --profile production  --platform ios

**Comment by mansmahamat** [comment]
Same for me

**Comment by OgzAkt** [comment]
+1

**Comment by ReMuSoMeGA93** [comment]
same here.

**Comment by sergeyshilin** [comment]
Same,

In the meantime, `eas build --non-interactive`  to skip the apple auth prompt and used cached signing credentials.

**Comment by ryanSoftwareEngineer** [comment]
oh no, it's happening to me too and i have a windows pc T__T

**Comment by sirusbaladi** [comment]
> eas build --non-interactive

what's the difference between that command and the normal eas build?

**Comment by sergeyshilin** [comment]
> what's the difference between that command and the normal eas build?

If you were able to successfully log in before, it will reuse your stored credentials instead of prompting again, and as a result, will be able to run a build.

**Comment by sirusbaladi** [comment]
> > what's the difference between that command and the normal eas build?
> 
> If you were able to successfully log in before, it will reuse your stored credentials instead of prompting again, and as a result, will be able to run a build.

awesome, works great but now have the same issue with trying to run: eas submit -p ios. 
Any way to go around it?

**Comment by iAhtasham** [comment]
I am still facing the same issue on eas-cli/7.3.0

PS D:\Projects\React Native> eas --version                                
eas-cli/7.3.0 win32-x64 node-v18.15.0
PS D:\Projects\React Native> eas build --profile production --platform ios
Loaded "env" configuration for the "production" profile: no environment variables specified. Learn more: https://docs.expo.dev/build-reference/variables/
√ Using remote iOS credentials (Expo server)

If you provide your Apple account credentials we will be able to generate all necessary build credentials and fully validate them.
This is optional, but without Apple account access you will need to provide all the missing values manually and we can only run minimal validation on them.   
√ Do you want to log in to your Apple account? ... yes

› Log in to your Apple Developer account to continue
√ Apple ID: ... *************
› Restoring session C:\Users\*****\.app-store\auth\***********\cookie
› Session expired Local session
› The password is only used to authenticate with Apple and never stored on EAS servers
  Learn more: https://bit.ly/2VtGWhU
√ Password (for ************): ... ***************
› Saving Apple ID password to the local Keychain
  Learn more: https://docs.expo.dev/distribution/security#keychain
√ Logged in New session
Authentication with Apple Developer Portal failed!
Apple provided the following error info:
Service not available because of maintenance activities, please try again after some time.
    Error: build command failed.

**Comment by pratiksvaidya** [comment]
Downgrading to 7.1.0 resolved the issue for me and I was able to both build and submit to the App Store.

```
npm uninstall eas-cli && npm install -g eas-cli@7.1.0
```

**Comment by ahmadtech199** [comment]
@pratiksvaidya Thank you so much, now it's working  🚀🚀🚀

**Comment by zachbwh** [comment]
@pratiksvaidya legend! thank you ❤️

**Comment by noctivityinc** [comment]
No good - ```You are on eas-cli@7.1.0 which does not satisfy the CLI version constraint in eas.json (>= 7.1.2)```

**Comment by noctivityinc** [comment]
Make sure to update your eas.json file as well in case you have a constraint :)

**Comment by StephenPalazzo** [comment]
Delete your eas.json file, and rerun eas build:configure

**Comment by brentvatne** [comment]
i released eas-cli@7.4.0 with a change to use an endpoint that isn't under maintenance. we'll follow up soon with a better approach that automatically switches between endpoints as needed. install the latest version of eas-cli to resolve this issue.
