### ISSUE TITLE
"eas build:resign" failed because of GitHub?

### ISSUE THREAD

**Issue by softlylove** [expo/eas-cli#2499]
### Summary

Hello, I encountered an error when running eas build:resign

Steps:

1. Trigger a build on Expo Cloud.
2. Register a new device after that build.
3. Run `eas build:resign`, everything good until error occurred: Failed to resign build, because GitHub builds cannot be retried.

I have searched Discord, Documents, GitHub Issues and Google, no idea what happened exactly 🤔

![image](https://github.com/user-attachments/assets/3dc37a81-0375-41bc-9253-211c452a7c12)

### Managed or bare?

Managed by Expo

### Environment

```sh
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.16.0 - ~/.nvm/versions/node/v20.16.0/bin/node
      npm: 10.8.1 - ~/.nvm/versions/node/v20.16.0/bin/npm
      Watchman: 2024.08.12.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 10.2.3
```

```sh
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check for legacy global CLI installed locally
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

### Error output

![image](https://github.com/user-attachments/assets/f816dc7e-5f62-4ada-9be1-293123545688)

### Reproducible demo or steps to reproduce from a blank project

1. Trigger a build on Expo Cloud.
2. Register a new device after that build.
3. Run `eas build:resign`, everything good until error occurred: Failed to resign build, because GitHub builds cannot be retried.

**Comment by szdziedzic** [comment]
>Failed to resign build, because GitHub builds cannot be retried

Hi, 

Yeah, I think that's true we currently don't support retrying or resigning builds triggered by our GitHub trigger on the EAS side (meaning the retry option on a build page for GH builds is not available, but it is for builds triggered using CLI, and you can't do `eas build:resign` targeting GH builds). 

The currently working retry mechanism for GH builds is through the GitHub UI
<img width="1278" alt="Screenshot 2024-08-19 at 12 34 35" src="https://github.com/user-attachments/assets/30381550-898f-4f1f-9b97-1d34e3185778">
but in reality, it will create a new build on the EAS side under the hood.

I believe we should add this information as a limitation to GitHub builds docs and make it more obvious in `eas build:resign` that you can't retry a given build because of XYZ when selecting it in an interactive select mode.
