### ISSUE TITLE
Why is git required for EAS Build?

### ISSUE THREAD

**Issue by leoskyrocker** [expo/eas-cli#281]
I'm running into an error in our CICD "EAS Build requires you to use a git repository for your project". While I understand you may want to do some checks when users are doing this locally and you want to avoid unintended changes to get into the build. It does not make as much sense in an automated setting where a pipeline checks out the source code from git, and packs it into an artifact then send it to the build stage.

Are you guys gonna consider allowing users to skip the git repo check explicitly?

**Comment by leoskyrocker** [comment]
on top of that... even when I try to initialize a git repo and commit all changes it's coming up with contradicting conclusion than `git status -uall`.

Please refer to screenshot for what I mean.
![Uploading Screenshot 2021-03-19 at 4.53.09 PM.png…]()

**Comment by wkozyra95** [comment]
We use `git` to 
- create an archive that is uploaded to workers (we don't want to upload anything that is gitignored)
- ensuring that the user is aware of changes that we are doing
- when building some tools e.g. sentry might rely on commit hash 

> Are you guys gonna consider allowing users to skip the git repo check explicitly?

No, because it would upload only committed changes to the worker which is not desired behavior. We could implement our own packaging that still respects gitignore, but it's sginifican't amount of work and I don't see what benefit it would be, if you are on CI and want to force that you can do this with one simple command by either committing everything or `git reset --hard`.

> on top of that... even when I try to initialize a git repo and commit all changes it's coming up with contradicting conclusion than git status -uall

We run `git status -s -uall` to verify if there are any changes (if there is sth on stdout we assume there are changes). In your case, `tee` is making changes to git repo

**Comment by leoskyrocker** [comment]
this sounds unreasonable - I don't see that everyone uses git. period. or question mark?

**Comment by leoskyrocker** [comment]
so I think in the case where git is being used it's an undesirable behavior because users could be uploading unexpected changes to the build, it's not an undesirable behavior for those who are not using git. So I can see how your argument is valid to those using git.

I was wondering if it's possible to just introduce a flag that bypasses the checks if the working dir is not a git repo, and if it's explicitly opted out by the user.

**Comment by wkozyra95** [comment]
> this sounds unreasonable - I don't see that everyone uses git. period. or question mark?

Almost all CI services (maybe expect some self-hosted ones) require git. You don't expect e.g. circle ci  to support projects that are not git repositories, but for EAS it is unreasonable? 

> In our CICD for example there is no existence of git, and the CLI is complaining about that. We had to hack around it to do a git init first.

Based on that I'm assuming that you are using git, but CI/CD pipeline is removing it? If that is the case can you share more about the use case/worflow? If there is a legitimate use case for that we would like to support it. We started with an implementation that required git because it solved some problems for us, but we didn't decide yet if that will be a requirement for the final EAS release. 

> so I think in the case where git is being used it's an undesirable behavior, it's not so much for those who are not using git. I can see how your argument is valid to those using git but also only valid to those using git.

We might support other version control systems in the future if there will be a need for that, but I don't see a reason to support the case without one.

> I was wondering if it's possible to just introduce a flag that bypasses the checks if the working dir is not a git repo, and if it's explicitly opted out by the user.

As explained in my previous comment this is not just a check, we use git for certain stuff and would need to reimplement that functionality to support that flag. Especially this does not seem to be worth it if there is a simple workaround for that case.

**Comment by leoskyrocker** [comment]
> If that is the case can you share more about the use case/worflow?
We use AWS Codepipeline.

A minimal setup of an AWS Codepipeline consists of two stages:
1. The source stage - In this stage, the source code is pulled in from any supported version control system (VCS), e.g. Subversion/Git/AWS S3/etc. The source code is pulled and an output artifact is generated the contains the source code.
2. The build stage - This is where the normal operations to build an application is done. In our case here, it will trigger `eas build` as part of the build process. Since this stage is VCS-agnostic, it would not have any of these platforms metadata included (e.g. for git the metadata is in the `.git` folder). It also may or may not contain the VCS tool's binary in the environment.
Because of that, we are now introducing over 5 lines into our buildstep to just instantiate git, and you may say that it's trivial, but it's definitely pollutes our build file a lot (13% increase in the overall build file) and really distracts future maintainers.
Moreover, right now we're assuming that git is available in the build stage. In the future, if they remove git from the environment (because it's not needed), we will need to add more lines to install git etc.

> As explained in my previous comment this is not just a check, we use git for certain stuff
Could you clarify what is the stuff that you rely git on, is it for Sentry which relies on the commit hash? I guess in that case we can't even benefit from that because the commit hash will be from a newly initialized repository?

**Comment by luyx2412** [comment]
Hi @wkozyra95 Can you give the solution how to disable or pass the git commit? Because I also same the issues, but don't have any solutions for that. In my case, I want to get the output URL from eas build. In my local worked great, but when run on pipeline ci showed the error "Your git working tree is dirty.".

![image](https://user-images.githubusercontent.com/8909619/112849484-5300e980-90d3-11eb-92fe-565d0f8997df.png)
![image](https://user-images.githubusercontent.com/8909619/112849366-31076700-90d3-11eb-8750-1bcd6a753a7f.png)

Thanks

**Comment by fson** [comment]
> 2. The build stage - This is where the normal operations to build an application is done. In our case here, it will trigger `eas build` as part of the build process. Since this stage is VCS-agnostic, it would not have any of these platforms metadata included (e.g. for git the metadata is in the `.git` folder). It also may or may not contain the VCS tool's binary in the environment.

Thanks for the explanation @leoskyrocker, this is really useful information. Would setting up the source action in CodePipeline with the **Full clone** option work for you? (See [Tutorial: Use full clone with a GitHub pipeline source](https://docs.aws.amazon.com/codepipeline/latest/userguide/tutorials-github-gitclone.html)). It seems that this would allow accessing the git metadata in the build action.

**Comment by brentvatne** [comment]
it's not required anymore, you can run `EAS_NO_VCS=1 eas build` and use `.easignore` in the same way you would use a `.gitignore` to tell eas-cli which files to leave out from your project when uploading it for a build
