### ISSUE TITLE
app name limitation

### ISSUE THREAD

**Issue by TakaoNarikawa** [expo/eas-cli#458]
I started to use EAS build because I want to build iOS app with `@stripe/stripe-react-native` ([doc](https://docs.expo.io/versions/latest/sdk/stripe/#limitations)) 
However, it requires me to use at least one alphabet character as app name in app.json.

```json
{
  "expo": {
    "name": "App Name", ← here
  }
}
```

```
$ eas build --profile development --platform ios

✔ Commit message: … update
    Error: "expo.name" needs to contain some 
    alphanumeric characters
```

I want to use only Japanese character like "あいう" and don't want to include alphabets in it.
With `expo build`, I could that.

Any suggestions?

maybe related

- https://github.com/expo/eas-cli/pull/280

**Comment by brentvatne** [comment]
here is how you can set a name for japanese locales: https://docs.expo.io/distribution/app-stores/#localizing-your-ios-app

by default, projects use english as the primary locale. this can be modified using config plugins, but we should have a better solution here.

**Comment by TakaoNarikawa** [comment]
Thanks for the reply!
I'll try the solution you suggested and I'm also looking forward to a better solution.

**Comment by koravski** [comment]
Hello @brentvatne,
I'm using EAS to build the app. I don't have problems with the classic build. But when I use non-english name I get error in "Run gradlew" phase during the build.
Is there such option like localizing my app but for Android build? For iOS I use the classic build.
Thanks.

**Comment by wodin** [comment]
@koravski for Android, this ugly workaround seems to work:

```diff
diff --git package.json package.json
index 283acfc..5589dc0 100644
--- package.json
+++ package.json
@@ -5,7 +5,8 @@
     "android": "expo start --android",
     "ios": "expo start --ios",
     "web": "expo start --web",
-    "eject": "expo eject"
+    "eject": "expo eject",
+    "eas-build-post-install": "sed -i.bak 's/app-name/真實應用名稱/' android/app/src/main/res/values/strings.xml && rm -f android/app/src/main/res/values/strings.xml.bak"
   },
   "dependencies": {
     "expo": "~42.0.1",
```

Otherwise look into `mods.android.strings` (see the [Default mods](https://docs.expo.dev/guides/config-plugins/#default-mods) section of the Config Plugin docs), and the [Android localization docs](https://developer.android.com/guide/topics/resources/localization).

**Comment by buraks** [comment]
@EvanBacon I see you have worked on fixing this issue last year.

I tried building my application on EAS for the first time and it failed because of non-English characters.

<img width="340" alt="image" src="https://user-images.githubusercontent.com/2693237/154671103-f336ba9c-016d-48be-b709-2f144fe844cf.png">

This is the error I get
<img width="1176" alt="image" src="https://user-images.githubusercontent.com/2693237/154671370-19317758-6e9e-4a74-892f-fa3286608208.png">

If I changed the name of the application in my config, the build is successful.

**Comment by wodin** [comment]
I can confirm that setting the "name" to "İftara Ne Kadar Kaldı?" causes the Android build to fail.
It's not clear to me why it fails, though.

The first error is on line 29 of `MainApplication.java`:
```java
package com.iftaranekadarkald;

import android.app.Application;
import android.content.Context;
import android.content.res.Configuration;
import androidx.annotation.NonNull;

import com.facebook.react.PackageList;
import com.facebook.react.ReactApplication;
import com.facebook.react.ReactInstanceManager;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.soloader.SoLoader;

import expo.modules.ApplicationLifecycleDispatcher;
import expo.modules.ReactNativeHostWrapper;

import com.facebook.react.bridge.JSIModulePackage;

import java.lang.reflect.InvocationTargetException;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {
  private final ReactNativeHost mReactNativeHost = new ReactNativeHostWrapper(
    this,
    new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;  // <----
    }

```

**Comment by odnhee** [comment]
How do I localize the app name in android?
