### ISSUE TITLE
Android Submit Flag --android-package has unexpected behaviour

### ISSUE THREAD

**Issue by joshhogg** [expo/eas-cli#488]
Based on the documentation, I would interpret the `--android-package` flag when running `eas submit` to supersede any value listed in app.json @ `expo.android.package`.

However, based on my testing, if a value is listed in the app.json, it is the value that is used. 

This makes it difficult to have scripts which will distribute an app for different environments to Google Play (ie: staging or preproduction builds)

By removing the entry @ `expo.android.package` the `--android-package` flag is honoured. 

Not sure if this is expected behaviour or not, but my intuition is that passing a flag directly to the command line should override any defaults.

**Comment by wkozyra95** [comment]
if you specify the android package manually it will override value from app.json, but apk/aab is still built with a different package name, so submit will fail because those values are mismatched

the android package is value defined during the build, if apk/aab already exists there is no way to override it.

**Comment by joshhogg** [comment]
Hey @wkozyra95,

This was not my experience. We have some code that overrides the config when building the apk/aab, say we build it with package `com.abc.staging`. We do this using an `app.config.js` file, reading values from `process.env`, which has some env vars like `OVERRIDE_BUNDLE_NAME`, overriding the config that is returned. This works great for the build process.

Later, when using eas-cli to submit, it doesn't read the `app.config.js`, which is expected and makes sense. So, instead we source the env file in the command line, and then when we call `eas submit` we pass in `--android-package=$OVERRIDE_BUNDLE_NAME`. This bundle name does not get used as the submission, instead it reads the value which is in `package.json`, which is our production value.

**Comment by wkozyra95** [comment]
Ah I see, sorry based on your description I assumed you wanted to override the package name in exiting binary during submit. 
Issue is fixed in PR linked above

>  This bundle name does not get used as the submission, instead it reads the value which is in package.json, which is our production value. If I remove the value in package.json

I assume you were thinking here about app.json not package.json ?

> Later, when using eas-cli to submit, it doesn't read the app.config.js, which is expected and makes sense. So, instead we source the env file in the command line, and then when we call eas submit we pass in --android-package=$OVERRIDE_BUNDLE_NAME.

If you are sourcing the same envs during submit as in build, then it should still work even with this bug, because the `android.package` in app.config.js should be overridden by `OVERRIDE_BUNDLE_NAME` assuming that app.config is written correctly
