### ISSUE TITLE
Whitespace in project name causes eas credentials to create an entitlements file with invalid name

### ISSUE THREAD

**Issue by kbrandwijk** [expo/eas-cli#496]
I'm afraid I might have ran into a little issue/bug with eas credentials for iOS. When I go through the motions to create them for the first time, eas updates the project file, and creates an entitlements file as well. For this, it uses the Product Name. However, when the Product name contains whitespace(s), this makes the project file invalid, causing XCode to says it's corrupt and won't open.

**Comment by dsokal** [comment]
@kbrandwijk I know it's been a long time since you created the issue but I tried to repro this today. It seems it works for me. Can you share the repro steps?

My steps:
- `expo init` + choose bare
- Open the iOS project in Xcode
- Edit the `Product Name` so it contains a whitespace (`abc 123`)
  <img width="877" alt="Screenshot 2021-11-15 at 16 43 48" src="https://user-images.githubusercontent.com/5256730/141810940-9120746c-3ef9-4d59-8eac-83ad28da1644.png">
- `eas build -p ios` + set up credentials

**Comment by kbrandwijk** [comment]
I'll see what I can dig up. Like you said, it's been a while :)

**Comment by kbrandwijk** [comment]
I was able to reproduce this if the project itself has a whitespace in the name.

**Comment by kbrandwijk** [comment]
1. Init a new project
2. Open in XCode
3. On the right, in the 'Identity and Type' panel, change the name to have a whitespace
4. A popup will show, telling you it'll rename a bunch of other things (project file, target etc.)
5. Run `eas credentials` to the point where it creates the entitlements file
6. Try opening the project in XCode again, and it won't.

**Comment by dsokal** [comment]
Thanks for the repro steps! Fixed in https://github.com/expo/expo-cli/pull/4007
