### ISSUE TITLE
EAS + Expo 42 apparently needs access to some sites which are on my dns blocklist

### ISSUE THREAD

**Issue by TheSilentHorizon** [expo/eas-cli#507]
When EAS tries to access an url which is on a blacklist, it results in this error:

```
Error: connect ECONNREFUSED 0.0.0.0:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1133:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '0.0.0.0',
  port: 443
}
```

I suggest, that at least you indicate that this is most like a DNS issue to help people who might stumble onto this error too. Took me a while to find a solution until I stumbled upon this thread:

[Error 443 on Expo Forums](https://forums.expo.io/t/eas-build-command-crashes-with-econnrefused/53554)

I think, the blacklist reacts due to some ad-related urls, is there any way to get a list of them? 

Or better, tell in the error which url couldnt be reached. This would be perfect.

**Temporary Hotfix:** Use a seperate DNS without blacklist. Worked fine for me.

**Comment by wkozyra95** [comment]
only expo api (`exp.host` domain) access should be required for cli to work, so if it's failing because of the different domain it's a bug, but without a way to reproduce it, I don't have any way to identify what is the problem.

Can you share your list of blocked sites?

> I think, the blacklist reacts due to some ad-related urls, is there any way to get a list of them?

I'm not aware of anything like that in eas-cli, the only other API we are using is amplitude analytics, you can disable it with `eas analytics off`, but it shouldn't be a reason for that error.

**Comment by lew** [comment]
see #505
