### ISSUE TITLE
Build issues adding Stripe w/ Apple Pay to ESA Build project

### ISSUE THREAD

**Issue by LinusU** [expo/eas-cli#523]
I'm trying to add `@stripe/stripe-react-native` to our EAS Build enabled Expo project, but running into the following problem:

```text
❌  error: Provisioning profile "*[expo] com.foo.bar AppStore 2021-07-21T16:00:00.000Z" doesn't support the merchant.foo.bar.applepay Merchant ID. (in target 'FooBar' from project 'FooBar')

❌  error: Provisioning profile "*[expo] com.foo.bar AppStore 2021-07-21T16:00:00.000Z" doesn't match the entitlements file's value for the com.apple.developer.in-app-payments entitlement. (in target 'FooBar' from project 'FooBar')

▸ ** ARCHIVE FAILED **
```

It seems to me that something failed during the capabilities sync or the provisioning profile generation 🤔 There are the steps that I followed:

- Ran `npm install @stripe/stripe-react-native`
- Added `"plugins": [["@stripe/stripe-react-native", { "merchantIdentifier": "merchant.foo.bar.applepay" }]],` to `app.json`
- Ran `eas build --platform ios`
  - Do you want to log in to your Apple account? **yes**
  - Synced capabilities: Enabled: Apple Pay Payment Processing
  - Fetched Apple distribution certificates
  - Fetched Apple provisioning profiles
  - Provisioning profile (id: XXXXXXXXX) is no longer valid
  - Fetched Apple provisioning profiles
  - Provisioning Profile - ID: XXXXXXXXX
  - Would you like to reuse the original profile? **no**
  - Generate a new Apple Provisioning Profile? **yes**
  - Created Apple provisioning profile

Then the build fails with the above error.

I tried running the same thing again, and I noticed that it again says "Provisioning profile (id: XXXXXXXXX) is no longer valid" so I'm thinking that something maybe goes wrong during the generation of the new provisioning profile, even though it says that it succeeded 🤔 

Will continue investigating tomorrow, am happy to answer any questions, and would appreciate any pointers!

**Comment by cruzach** [comment]
Thanks for the issue report! Have you set up Apple Pay according to [Stripe's docs](https://stripe.com/docs/apple-pay?platform=react-native#merchantid)? Namely, `Register for an Apple Merchant ID` and `Create a new Apple Pay certificate`

**Comment by EvanBacon** [comment]
The auto capability feature currently does not support (a feature I call) "Capability IDs". These IDs are used for payments, app groups, and iCloud containers (each is prefixed with a certain string and must be unique).

Currently eas build will just enable/disable capabilities based on the entitlements file. Because we aren't registering merchant IDs, then linking them to the bundle identifier capabilities, the provisioning profile doesn't match the entitlements, which results in a build crash.

One way around this is to go to https://developer.apple.com/account/resources/identifiers/list and configure the bundle ID manually, or to do the same in Xcode. 

I've been kicking around the idea of automatically registering and linking IDs, but it has two blockers:
- What if the user mistyped their merchant ID and we accidentally register it, would this interaction be undesirable?
- The capability ID API is not currently supported by App Store Connect tokens, which we plan to add soon for CI automation. This would mean that users would have a different experience from the local CLI than they would from a cloud variation.

Regardless, I can work on a PR just so we can feel out if it makes sense or not. Sorry for the inconvenience.

**Comment by LinusU** [comment]
The problem was indeed that there the merchant id was not added to the Apple Pay capability:

<img width="1039" alt="Screenshot 2021-07-22 at 12 55 29" src="https://user-images.githubusercontent.com/189580/126628640-b71dd9cd-18d9-46ae-8efd-13b851633634.png">

@EvanBacon thank you for the quick implementation! 😍 Will try it out now, and also post some more thoughts that I have to that PR
