### ISSUE TITLE
eas submit does not use environment variables from eas.json

### ISSUE THREAD

**Issue by gerwim** [expo/eas-cli#835]
### Summary

When running `eas submit --platform ios --profile tst --latest` it returns an error.

### Managed or bare?

Managed

### Environment

 EAS CLI 0.40.0 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 14.18.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.15 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
    Utilities:
      Git: 2.31.1.
    npmPackages:
      @expo/webpack-config: ^0.16.2 => 0.16.4
      expo: ^43.0.0 => 43.0.0
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Project workflow: managed

### Error output

```
Failed to resolve bundleIdentifier in the Xcode project: Specify "ios.bundleIdentifier" in app.config.ts or app.json and run this command again..
Specify "ios.bundleIdentifier" in app.config.ts or app.json and run this command again.
```

### Reproducible demo or steps to reproduce from a blank project

Init an EAS project with the following files:

eas.json
```
{
    "cli": {
      "version": ">= 0.38.3"
    },
    "build": {
      "development": {
        "developmentClient": true,
        "distribution": "internal"
      },
      "preview": {
        "distribution": "internal"
      },
      "tst": {
        "env": {
            "BUNDLE_IDENTIFIER": "my.app.development"
          }
      }
    },
    "submit": {
      "tst": {}
    }
  }
```
app.config.js
```
export default ({ config }) => {
    return {
        ...config,
        ios: {
            ...config.ios,
            bundleIdentifier: process.env.BUNDLE_IDENTIFIER,
        }
    };
};
```

It's probably the same underlying issue as https://github.com/expo/eas-cli/issues/820.

When running an `eas build` with `--auto-submit` it works. But running `eas submit` seperately from the build does not.

**Comment by brentvatne** [comment]
this is expected behavior

**Comment by hfllr** [comment]
Posting here because it's not an issue but more a inconsistency in the docs @brentvatne : [here](https://docs.expo.dev/eas-update/migrate-to-eas-update/#additional-possible-migration-steps) is described: "Remove any code that references Constants.manifest. That will now always return null." but [here](https://docs.expo.dev/eas-update/environment-variables/#creating-an-envts-file-to-get-environment) it is described how to get the env variables from eas.json using Constants.manifest (which is not working).

Sorry if it's the wrong place to share this, but I wasn't sure where to post this. Its driving me crazy because I couldnt figure out a way to retreive the env variables of eas.json

**Comment by Userrrfriendly** [comment]
@hfllr So did you have any luck retrieving the env variables of eas.json? I'm still struggling with this issue.

**Comment by bartvanandel** [comment]
We are having a bit of trouble getting `eas submit` to use the correct configuration due to this lack of support for `env` in the `submit` configuration as well.

We use some logic in `app.config.ts` to create an runtime environment specific app id (e.g. "com.example.app" for prod, "com.example.app.dev" for dev; same with app name so Apple doesn't complain). However, this only works for `eas build` and `eas update` (last one untested by us so far). It would be very beneficial if environment can be read from the `submit` config as well, e.g.:

```json5
{
  build: {...},
  submit: {
    base: {...},
    dev: {
      extends: 'base',
      env: {
        APP_ENV: 'dev'
      },
    },
    prod: {
      extends: 'base',
      env: {
        APP_ENV: 'prod'
      }
    },
    'prod:beta': {
      extends: 'prod',
      android: {
        track: 'internal',
      },
      // etc
    },
  },
}
```

**Comment by nathalia-rus** [comment]
Agree with @bartvanandel - this would be super appreciated and it's the only reason why we are not using EAS submit. I see the issue is closed; are there any plans in the future to enable this?

**Comment by hfllr** [comment]
@Userrrfriendly  sorry for the late reply, but no not yet. I'm currently using 'process.env.NODE_ENV' inside the code to make the necessary distinction where needed. This doesn't allow for custom environments, but at least distinguishes dev from prod.

**Comment by tsugumi-sys** [comment]
@buscanopaul 
I'm having a same issue, do you find some solution?

**Comment by evrimfeyyaz** [comment]
This makes EAS Submit virtually unusable when using environment variables from the Expo dashboard.

**Comment by evrimfeyyaz** [comment]
@brentvatne This makes EAS Submit virtually unusable when using environment variables.

**Comment by steve4835** [comment]
I would also like to see this implemented.  I agree with @evrimfeyyaz, EAS Submit is severely limited without support for environment variables.
