### ISSUE TITLE
Terminal-link usage

### ISSUE THREAD

**Issue by barthap** [expo/eas-cli#89]
Don't want this discussion to be forgotten:

https://github.com/expo/eas-cli/pull/65#issuecomment-732108522

cc @wkozyra95 @brentvatne

**Comment by brentvatne** [comment]
### the problem

terminal-link's `isSupported` property is `true` for some terminals (eg: "terminator") where it is not indeed supported. the result is that the user will see some underlined text, but not have any way of actually clicking the link. this is a bad experience. but should we lower the ceiling for the quality of experience in order to accommodate the worst case scenarios?

### possible solutions

- upstream improvements to `isSupported`
- use a wrapper like [this one from expo-cli](https://github.com/expo/expo-cli/blob/master/packages/expo-cli/src/commands/utils/TerminalLink.ts) and default to using the fallback on windows and linux (where we're more likely to run into unsupported terminals)
- possibly make exceptions to the previous rule if we can easily detect that a terminal will definitely support terminal-link
- add an env var that users can set to override the default - `EXPO_USE_TERMINAL_LINK=1` will always trust terminal-link's `isSupported` property, and `EXPO_USE_TERMINAL_LINK=0` will always use the fallback

**Comment by wkozyra95** [comment]
1) it's not a problem with `isSupported` itself, doc of terminal-link also list terminator as supported
2) it's probably the easiest solution, instead of checking based on platform maybe we could just whitelist specific terminals we are sure that they work
3) as in point 2
4) env could be useful for debuginng during development if everything looks correct on unsupported terminals, but for users, it wouldn't be a good experience, those links are usually linking to docs or fyi page, so we need to make sure they are alwayss acessible
