### ISSUE TITLE
eas device:create gives never ending gibberish screen

### ISSUE THREAD

**Issue by abhitheawesomecoder** [expo/eas-cli#901]
### Summary

eas device:create gives never ending gibberish scree
![Screenshot 2022-01-11 at 12 12 02 AM](https://user-images.githubusercontent.com/3944526/148822338-ce94f540-aa3d-498d-bbb8-d5eb30b12d43.png)
n

### Managed or bare?

bare

### Environment

waiting for command to complete

### Reproducible demo or steps to reproduce from a blank project

eas device:create gives never ending gibberish screen

**Comment by abhitheawesomecoder** [comment]
finally I have to Ctrl+C end the command and hers the eas diagnostics log

  EAS CLI 0.43.0 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 17.2.0 - /usr/local/bin/node
      npm: 8.1.4 - /usr/local/bin/npm
    Utilities:
      Git: 2.30.1 - /usr/bin/git
    npmPackages:
      @expo/webpack-config: ^0.16.13 => 0.16.15 
      expo: ~43.0.2 => 43.0.4 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.43.0
      expo-cli: 5.0.3
    Project workflow: managed

**Comment by kbrandwijk** [comment]
Can you show the _beginning_ of the gibberish?

**Comment by ide** [comment]
The root cause of this issue is that EAS CLI indirectly depends on a package called colors. The author of that package intentionally published new versions in bad faith (see original post) and npm has since pinned `colors@latest = 1.4.0` to fix this. You can fix this issue on your own computer by uninstalling and reinstalling EAS CLI.

There are two dependencies in EAS CLI that used colors. One has removed colors and the other has pinned its use of colors to 1.4.0.

We have also verified that EAS CLI does not depend, directly or indirectly, on any other packages owned by the person who published the malicious updates.
