### ISSUE TITLE
EAS Build Breaks React Navigation Drawer & react-native-draggable-flatlist. Both Work Locally

### ISSUE THREAD

**Issue by jdubs1994** [expo/eas-cli#949]
### Summary

EAS Build breaks react-navigation drawer slide out and slide in via pulling from the left side of the screen to slide it into play. Tapping on the screen behind the drawer also no longer closes the drawer. This works perfectly fine locally via expo run on a physical device or a simulator. As soon as we create an EAS build eas build -p ios and push it to testflight it no longer works. 

This is the same case for https://github.com/computerjazz/react-native-draggable-flatlist, the list works perfect locally but breaks as soon as we make an EAS build.

Drawer: https://reactnavigation.org/docs/drawer-based-navigation/

Any ideas on what could be going on?

### Managed or bare?

Managed

### Environment

`  EAS CLI 0.42.4 environment info:
    System:
      OS: macOS 12.0
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.0/bin/yarn
      npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Utilities:
      Git: 2.30.1 - /usr/bin/git
    npmPackages:
      expo: ^43.0.0 => 43.0.3
      expo-updates: ~0.10.13 => 0.10.15
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      eas-cli: 0.42.4
      expo-cli: 4.13.0
    Project workflow: managed`

### Reproducible demo or steps to reproduce from a blank project

Cannot reproduce in the simulator and cant give a demo as its on testflight for internal users only.

**Comment by wkozyra95** [comment]
Does it work locally with latest expo-cli? (When testing delete android/ios directories to make sure you are testing on the clean state)
You can also specify `expoCli` field in eas.json build profile to test that in the other direction`

The other thing you can try is to build with `eas build --local` to verify what is responsible for different behavior(build process or environment)

You are comparing debug build create with run:ios to release build created on eas. Is there anything that would suggest that issue is on eas side?

**Comment by jdubs1994** [comment]
Hey, the issue I believe we were running into was not pushing the ios folder up to our repo. Once we that it seemed to fix the issue. My thought was that the EAS Build would regenerate it on expo servers so I'm not sure entirely why that fixed it.

**Comment by wkozyra95** [comment]
if you have android/ios directories in gitignore then your project was treated as managed and eas build generated it for you, after you committed those directories to repo your project becomes bare workflow (aka ejected) and eas is building it as it is. 
If that fixed it for you then most likely you had some local changes in your android/ios directories that changed the behavior.

Other than potential local changes, the main difference in your case is expo-cli version that you are using is 4.13.0 and eas build runs 5.0.3, so `prebuild` command could introduce that change.

**Comment by CRIMSON-CORP** [comment]
I am also experiencing a build fail for android, and it seems its because of `react-native-navigation`

this happens after I run `eas build --platform android`

here is a snip of my build log in my Expo dashboard 

`  - expo-updates (0.11.6)`
  `- react-native-reanimated (2.3.3)`
`[stderr] FAILURE: Build completed with 2 failures.`
`[stderr] 1: Task failed with an exception.`
`[stderr] -----------`
`[stderr] * Where:`
`[stderr] Build file '/home/expo/workingdir/build/node_modules/react-native-navigation/lib/android/app/build.gradle' line: 5`
`[stderr] * What went wrong:`
`[stderr] A problem occurred evaluating project ':react-native-navigation'.`
`[stderr] > Plugin with id 'kotlin-android' not found.`
`[stderr] * Try:`
`[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.`
`[stderr] ==============================================================================`
`[stderr] 2: Task failed with an exception.`
`[stderr] -----------`
`[stderr] * What went wrong:`
`[stderr] A problem occurred configuring project ':react-native-navigation'.`
`[stderr] > compileSdkVersion is not specified. Please add it to build.gradle`
`[stderr] * Try:`
`[stderr] Run with --stacktrace option to get the stack trace. Run with --info or`
`[stderr] --debug option to get more log output. Run with --scan`
`[stderr] to get full insights.`
`[stderr] ==============================================================================
[stderr] * Get more help at https://help.gradle.org`

**Comment by tamis-laan** [comment]
@CRIMSON-CORP 

Same problem here, found a solution/workaround?

**Comment by Rafa-Django** [comment]
Same problem

**Comment by alexpaulooliveira** [comment]
Same problem here!!!
